import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { SITE, absoluteUrl } from "@/lib/site";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy Policy | iinteliprox" }, { name: "description", content: "How iinteliprox handles personal information, cookies and inquiries." }, { property: "og:url", content: absoluteUrl("/privacy") }], links: [{ rel: "canonical", href: absoluteUrl("/privacy") }] }),
  component: PrivacyPage,
});

function PrivacyPage() { return <div className="min-h-screen"><SiteNav /><main className="mx-auto max-w-3xl px-4 pb-24 pt-32 sm:px-6 sm:pt-40"><div className="eyebrow">Legal</div><h1 className="mt-4 font-display text-5xl">Privacy Policy</h1><p className="mt-5 text-sm text-muted-foreground">Last updated: July 22, 2026</p><div className="mt-12 space-y-10 leading-relaxed text-muted-foreground"><section><h2 className="font-display text-3xl text-foreground">Information we collect</h2><p className="mt-3">When you contact us, book a call, message us on WhatsApp, or use our forms, we may collect your name, company, email address, phone number, country, service requirements, budget and project details. Our site may also use essential browser storage to remember cookie choices.</p></section><section><h2 className="font-display text-3xl text-foreground">How we use information</h2><p className="mt-3">We use information to respond to inquiries, prepare proposals, deliver services, manage client relationships, maintain security and improve our website. We do not sell personal information.</p></section><section><h2 className="font-display text-3xl text-foreground">Cookies and third parties</h2><p className="mt-3">Essential storage is used for cookie consent. If we add Google Analytics, Meta Pixel, Calendly, WhatsApp, or similar services, optional analytics or marketing tools will only load after consent where required. Those providers process data under their own privacy policies.</p></section><section><h2 className="font-display text-3xl text-foreground">Retention and your rights</h2><p className="mt-3">We retain inquiry and client records only as long as reasonably needed for the purposes above or legal obligations. Subject to applicable law, you may request access, correction, deletion, restriction or withdrawal of consent by contacting us.</p></section><section><h2 className="font-display text-3xl text-foreground">Contact</h2><p className="mt-3">For privacy requests, email <a className="text-brand underline" href={`mailto:${SITE.email.business}`}>{SITE.email.business}</a> or write to {SITE.address.full}.</p></section></div></main><SiteFooter /></div>; }
