import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { SITE, absoluteUrl } from "@/lib/site";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service | iinteliprox" }, { name: "description", content: "Terms governing iinteliprox services and website use." }, { property: "og:url", content: absoluteUrl("/terms") }], links: [{ rel: "canonical", href: absoluteUrl("/terms") }] }),
  component: TermsPage,
});

function TermsPage() { return <div className="min-h-screen"><SiteNav /><main className="mx-auto max-w-3xl px-4 pb-24 pt-32 sm:px-6 sm:pt-40"><div className="eyebrow">Legal</div><h1 className="mt-4 font-display text-5xl">Terms of Service</h1><p className="mt-5 text-sm text-muted-foreground">Last updated: July 22, 2026</p><div className="mt-12 space-y-10 leading-relaxed text-muted-foreground"><section><h2 className="font-display text-3xl text-foreground">Services and agreements</h2><p className="mt-3">Project scope, deliverables, timelines, fees and acceptance criteria are defined in the applicable written proposal or agreement. Website content is informational and does not itself form a contract.</p></section><section><h2 className="font-display text-3xl text-foreground">Payments and refunds</h2><p className="mt-3">Invoices are due as stated in the applicable agreement. Deposits, milestones and refunds are governed by that agreement. Work already completed, third-party fees and reserved capacity are generally non-refundable unless the agreement says otherwise.</p></section><section><h2 className="font-display text-3xl text-foreground">Intellectual property</h2><p className="mt-3">Each party retains ownership of its pre-existing materials. Upon full payment, client-specific deliverables transfer or are licensed as specified in the project agreement; our reusable tools, methods and open-source components remain ours or their respective licensors&apos;.</p></section><section><h2 className="font-display text-3xl text-foreground">Client responsibilities</h2><p className="mt-3">Clients must provide accurate information, timely feedback, required access and rights to supplied content. Delays caused by missing client inputs may affect timelines and fees.</p></section><section><h2 className="font-display text-3xl text-foreground">Liability</h2><p className="mt-3">To the maximum extent permitted by law, iinteliprox is not liable for indirect, incidental, special or consequential loss. Our total liability related to a service is limited to fees paid for that service in the preceding three months, except where law does not allow a limitation.</p></section><section><h2 className="font-display text-3xl text-foreground">Governing law and contact</h2><p className="mt-3">These terms are governed by the laws of India, with courts in Lucknow, Uttar Pradesh having jurisdiction where permitted. Questions: <a className="text-brand underline" href={`mailto:${SITE.email.business}`}>{SITE.email.business}</a>.</p></section></div></main><SiteFooter /></div>; }
